//import { Link } from "react-router-dom"
import styles from './PaginaNormativa.module.css';
import { BarraNavegacion, FondoPaginas, Footer} from '../../components';



function PaginaNormativa()
{
    return(
        <>
            <div className={styles.content}>
                <BarraNavegacion></BarraNavegacion>
                <FondoPaginas>
                    <section className={styles.contenedor} >
                        <h1>Colegio de Lincenciados en Turismo</h1>
                        <ul>
                            <li>En 1988 se promulga la <a href="https://drive.google.com/file/d/1UVLIDCCUq_s2WSohwUGVvokUy3IzqpPU/view?usp=sharing">Ley N°24915</a> y su <a href="https://drive.google.com/file/d/1PCI-vPMGrvVNIG4nHoM69bAXBTI9PPPx/view?usp=sharing">Estatuto D. S. Nº 012-90-ICTI-TUR</a> que crea El Colegio de Licenciados en Turismo del Perú. </li>
                            <li>El 23 de abril de 2021 se promulga la <a href="https://drive.google.com/file/d/1mJ-Ce3zDjNCVMxNV6xx2a9r9GyVl4zSs/view?usp=sharing">Ley N°31172</a> que actualiza a la Ley N°24915 y crea los Colegios de profesionales en Turismo en cada región del país. es importante mencionar que a la fecha, esta Ley N°31172 no ha sido reglamentada por la Junta de Decanos quienes deben formular el estatuto institucional el cual deberá ser aprobado por el MINCETUR por resolución ministerial</li>
                        </ul>
                        <h1> Agencias de Viajes</h1>
                        <ul>
                            <li><a href="https://1drv.ms/b/s!Api7z-jSaP6-lh7LV9gnCY3NmZnV?e=UUCcOr">Decreto Supremo N° 005-2020-MINCETUR. – Reglamento de Agencias de Viajes y Turismo.</a> Derogando el <a href="https://1drv.ms/b/s!Api7z-jSaP6-lhyKEKY4cwl-I7YZ?e=3kMxFl">Decreto Supremo N° 004-2016-MINCETUR</a>. Consta de seis capítulos, veinticuatro artículos, diecinueve disposiciones complementarias finales y seis disposiciones complementarias transitorias.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/DS_001_2019_MINCETUR_Regl_Seguridad_STA.pdf">Decreto Supremo N° 001-2019-MINCETUR.</a> – Decreto Supremo que dispone la modificación de diversos artículos de los Reglamentos de Seguridad para la Prestación del Servicio Turístico de Aventura y de Canotaje Turístico.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Decreto_Supremo_NRO_011_2017_MINCETUR_CT-AGV.pdf">Decreto Supremo N° 011-2017-MINCETUR, 31.07.2017</a>, que modifica el Reglamento de Canotaje Turístico y Reglamento de Agencias de Viajes y Turismo.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RVM_N046_2016_MINCETUR_VMT.pdf">Resolución Viceministerial N° 046-2016 MINCETUR-VMT</a> – Aprueban los formatos y los documentos señalados en el Reglamento de Agencias de Viajes y Turismo, aprobado por el Decreto Supremo N° 004-2016-MINCETUR, que en anexos del 1 al 3 forman parte integrante de la presente Resolución Viceministerial.</li>
                            <ul>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo_01DJ_AGVT_13JUL2016.pdf">Anexo N° 01 – Declaración Jurada</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo_02_CONSTANCIA2016_AGVT_DGPDT_13JUL2016.pdf">Anexo N° 02 – Constancia</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo_03_placa_inidicativa.pdf">Anexo N° 03 – Placa Indicativa</a></li>
                            </ul>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RVM_N048_2016_MINCETUR_VMT_GruposChinos.pdf">Resolución Viceministerial N° 048-2016-MINCETUR-VMT</a> – Aprueban requisitos que deberán presentar las Agencias de Viajes y Turismo que deseen formar parte de la Lista de Agencias de Viajes y Turismo, recomendadas para facilitar viajes de grupos turísticos organizados chinos al Perú.</li>
                        </ul>
                        <h1>Establecimientos de hospedaje</h1>
                        <ul>
                            <li><a href="">Decreto Supremo N° 005-2021-MINCETUR</a> se modifica el Reglamento de Establecimientos de Hospedaje adecuándolo a las disposiciones contenidas en la Ley N° 30802, Ley que establece condiciones para el ingreso de niñas, niños y adolescentes a establecimientos de hospedaje.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Decreto_Supremo_NRO_009_2017_MINCETUR_REH.pdf">Decreto Supremo N° 009-2017-MINCETUR, 31.07.2017</a>, que modifica el Reglamento de Restaurantes y Reglamento de Establecimientos de Hospedaje.</li>
                            <li>Reglamento de establecimientos de hospedaje – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Decreto_Supremo_NRO_001_2015_MINCETUR_REH.pdf">Decreto Supremo N° 001-2015-MINCETUR, 09.06.2015</a>, establece las disposiciones para la clasificación, categorización, operación y supervisión de los establecimientos de hospedaje; así como las funciones de los órganos competentes en dicha materia, así como, la obligación de presentar una Declaración Jurada de cumplimiento de las condiciones mínimas para la prestación del servicio. Establece la clasificación de Hotel, Apart-Hotel, Hostal y Albergue, que podrán ser ostentados por los establecimientos que cumplan con los requisitos de infraestructura en la Norma A.030 Hospedaje del Título III del Reglamento Nacional de Edificaciones aprobado por RM N° 005-2019-VIVIENDA Resolución Ministerial que modifica la Norma Técnica A.030 “Hospedaje” del Reglamento Nacional de Edificaciones.</li>
                        </ul>
                        <h1><i>Anexos</i></h1>
                        <ul>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Mod_RVM_022_2016_MINCETUR_VMT.pdf">Resolución Viceministerial N° 022-2016-MINCETUR-VMT</a>, Resolución que modifica los anexos N° 1 y N° 13 referidos en el artículo 1 de la Resolución Viceministerial N° 24-2015-MINCETUR-VMT.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RV_Nro_024_2015_MINCETURVMT.pdf">Resolución Viceministerial Nro 024-2015-MINCETUR/VMT</a></li>
                            <ul>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/DJ_Hospedaje_Modificado_RVM_N022_2016.pdf">Anexo 1 – Establecimiento de Hospedaje – Declaración Jurada</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Formato_Anexo_2_constanciaDJ.doc">Anexo 2 – Formato de constancia de presentación de Declaración Jurada de cumplimiento de requisitos mínimos de establecimiento de hospedaje</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_H2y1.doc">Anexo 3 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Hotel 1 o 2 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_H3.doc">Anexo 4 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Hotel 3 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_H4.doc">Anexo 5 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Hotel 4 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_H5.doc">Anexo 6 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Hotel 5 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_AH_3.doc">Anexo 7 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Apart Hotel 3 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_AH_4.doc">Anexo 8 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Apart Hotel 4 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_AH_5.doc">Anexo 9 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Apart Hotel 5 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/formato_CLASIFICACION_EH_Hs_2y1.doc">Anexo 10 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Hostal 1 y 2 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_Hs_3.doc">Anexo 11 – Establecimiento de Hospedaje – Formato para Clasificación y Categorización de Hostal 3 estrellas</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/FORMATO_CLASIFICACION_EH_ALBERGUE.doc">Anexo 12 – Establecimiento de Hospedaje – Formato para Clasificación como Albergue</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo13_DJ_Categorizados_Modificado_RVM_N022_2016.pdf">Anexo 13 – Declaración Jurada Anual de Cumplimiento de los Requisitos Mínimos de Clase y/o Categoría</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo_14_DJ_Transferencia_EH.doc">Anexo 14 – Declaración Jurada de Transferencia del Establecimiento de Hospedaje</a></li>
                                <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Formato_Anexo_15_PlacaIndicativa.doc">Anexo 15 – Forma y Característica de las Placas Indicativas de los establecimientos de hospedaje</a></li>
                            </ul>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RM_151_2001.pdf">Reglamento de Calificadores de Establecimientos de Hospedaje (Resolución Ministerial N° 151-2001-ITINCI/DM, 30.07.2001)</a> – Define las funciones, procedimiento para la evaluación y designación de Calificadores de Establecimientos de Hospedaje, quienes tiene la función de emitir Informes Técnicos con el fin de solicitar la condición de establecimiento de Hospedaje Clasificado y/o Categorizado.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Formularios_TUPA_MINCETUR.zip">Formulario F- 012.
                            Inscripción como Calificador de Establecimiento de Hospedaje</a></li>
                        </ul>
                        <h1>Alojamiento en casas particulares y centros educativos</h1>
                        <ul>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/DS_1095_ITINCI.pdf">Reglamento de Autorización y Registro de Casas Particulares casas particulares y centros educativos (D.S. 010-95-ITINCI, 04.05.95)</a>. Este dispositivo establece los requisitos mínimos que deberán cumplir las casas particulares, universidades e institutos superiores, para brindar el servicio de alojamiento.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RD_N0011_95.pdf">Requisitos que deberán cumplir los establecimientos que brindan servicio de alojamiento (Resolución Ministerial N° 0011-95-MITINCI/VMTINCI/DNT DEL 16.05.1995)</a> Este dispositivo establece los requisitos mínimos que deberán cumplir las casas particulares, universidades e institutos superiores, para brindar el servicio de alojamiento.</li>
                        </ul>   
                        <h1>Turismo de Aventura</h1>
                        <ul>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/DS_001_2019_MINCETUR_Regl_Seguridad_STA.pdf">Decreto Supremo N° 001-2019-MINCETUR.</a> – Decreto Supremo que dispone la modificación de diversos artículos de los Reglamentos de Seguridad para la Prestación del Servicio Turístico de Aventura y de Canotaje Turístico.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RVM_04_2019_MINCETUR_VMT.pdf">Resolución Viceministerial N° 04-2019-MINCETUR-VMT</a> – Adecuar los formatos y los documentos mencionados en el Reglamento de Seguridad para la Prestación del Servicio Turístico de Aventura aprobado mediante Decreto Supremo Nº 005-2016-MINCETUR.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Decreto_Supremo_005_2016_MINCETUR_SEG-AVENTURA.pdf">Reglamento de Seguridad para la Prestación del Servicio Turístico de Aventura</a> – Decreto Supremo N° 005-2016-MINCETUR. – Reglamento que establece las disposiciones administrativas para la seguridad en la prestación del servicio de turismo de aventura, a través de las Agencias de Viajes y Turismo debidamente autorizadas por el Órgano Competente.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RM_Nro_083_2018_Modalidadesturismodeaventura.pdf">Resolución Ministerial N° 197-2021-MINCETUR.</a> Derogando la <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RM_Nro_083_2018_Modalidadesturismodeaventura.pdf">Resolución Ministerial N° 083-2018-MINCETUR</a> – Aprueban modalidades de Turismo de Aventura: Ala Delta, Barranquismo, Buceo, Cabalgata, Canopy / Zipline, Ciclismo, Columpio extremo, Esquí, Escalada, Escalada en árboles, Espeleología o Exploración de cuevas, Kayak, Kite Surf, Parapente, Puente tibetano, Puentismo, Rápel, Sandboard, Stand up paddle, Tabla a vela, Vía ferrata y Zipline bike.</li>
                            <li><a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/RVM_NRO_03_2018_FormatosReglamentoturismodeaventura.pdf">Resolución Viceministerial N° 03-2018-MINCETUR</a> – Aprobar los formatos y los documentos señalados en el Reglamento de Seguridad para la Prestación del Servicio Turístico de Aventura, aprobado por el Decreto Supremo Nº 005-2016-MINCETUR, que en anexos del 1 al 9 forman parte integrante de la presente Resolución Viceministerial.</li>
                            <ul>
                                <li>Anexo 1 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo1_DS_001_2019_MINCETUR_MIO.pdf">Manual interno de operación</a></li>
                                <li>Anexo 2 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo2_DS_001_2019_MINCETUR_PMR.pdf">Programa de manejo de riesgos</a></li>
                                <li>Anexo 3 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo3-RVM-03-2018-PME.pdf">Programa de mantenimiento de equipos</a></li>
                                <li>Anexo 4 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo4_DS_001_2019_MINCETUR_RIncidentes.pdf">Registro de incidentes</a></li>
                                <li>Anexo 5 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo5-RVM-03-2018-CPSPE.pdf">Compromiso de prestar servicios con personal especializado</a></li>
                                <li>Anexo 6 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo6-RVM-03-2018.pdf">Compromiso de prestar servicios con equipos idoneos</a></li>
                                <li>Anexo 7 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo7-RVM-03-2018.pdf">Condiciones para prestar el servicio</a></li>
                                <li>Anexo 8 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo8-RVM-03-2018.pdf">Condiciones para prestar el servicio a menores de edad</a></li>
                                <li>Anexo 9 – <a href="https://web.archive.org/web/20191217153957/https:/www.mincetur.gob.pe/wp-content/uploads/documentos/turismo/funciones_y_normatividad/normatividad/prestadores_servicios_turisticos/Anexo9-RVM-03-2018.pdf">Relación del equipo de primeros auxilios</a></li>
                            </ul>
                        </ul>  
                    </section>
                </FondoPaginas>
                <Footer></Footer>
            </div>
        </>
    )
}

export default PaginaNormativa